version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
    - 8800:80
    links:
    - php
    volumes:
    - ./www/html/:/var/www/html/
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php/
    volumes:
    - ./www/html/:/var/www/html/ 
    links:
      - mysql
  mysql:    
      image: mysql:8.0.12  
      container_name: mysql-container  
      volumes_from:  
        - mysql-data  
      environment:  
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306
  mysql-data:    
      image: mysql:8.0.12  
      container_name: mysql-data-container  
      volumes:  
        - /opt/mysql:/var/lib/mysql  
      command: "true"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
    ports:
      - 8000:80